### ISSUE TITLE
Update trimmomatic_merge / samples_trimmed.txt to include unpaired reads?

### ISSUE THREAD

**Issue by photocyte** [transXpress/transXpress-snakemake#10]
It seems like Trinity might be able to use the unpaired reads from a given library if specified in the samples.txt file?  See here:
https://github.com/trinityrnaseq/trinityrnaseq/wiki/Running-Trinity

Presumably the solution would be (after trimmomatic trimming):
Line 1: trimmomatic paired F & R reads
Line 2: trimmomatic unpaired reads from F reads(with column 4 left blank)
Line 3: trimmomatic unpaired reads from R reads (with column 4 left blank)

And then column 1,2, between Line 1,2,3 would be the same?

Currently the rnaspades YAML script just derives the unpaired read file name from the paired read file names, but this isn't so ideal (a bit fragile, bad practice)

**Comment by tomas-pluskal** [comment]
I have done that initially, but Trinity refuses to run if you combine paired and unpaired reads in the samples.txt, at least in the current version.

**Comment by photocyte** [comment]
Yes I saw some of your comments, thought you might have worked on it.  Reported to Trinity devs?

For the rnaspades side of things, I'll do some tests on some error handling when the number of reads in the unpaired file is zero.  I expect, trimmomatic should always produce the unpaired file, so it is safe albeit a bit haphazard to hardcode the unpaired reads suffix, as long as the case of the file having no reads is handled.

**Comment by tomas-pluskal** [comment]
Don't you think we should just ignore the unpaired files produced by trimmomatic, to be consistent with the trinity pipeline?

**Comment by photocyte** [comment]
Sure, will comment that section out

**Comment by tomas-pluskal** [comment]
https://github.com/trinityrnaseq/trinityrnaseq/issues/654

**Comment by tomas-pluskal** [comment]
I guess we can close this based on Brian's response
