### ISSUE TITLE
Split snakemake/nextflow shared scripts (annotation/yaml making) into separate files?

### ISSUE THREAD

**Issue by photocyte** [transXpress/transXpress-snakemake#11]
Seems like they could be shared with git submodules?  Would help ensure they stay up to date, and ensure they snakemake/nextflow versions are behaving the same way

**Comment by tomas-pluskal** [comment]
Possible, but IMHO it violates the KISS principle...

**Comment by photocyte** [comment]
Can call this a 2.0 feature.  I have no clue how hard to implement it would be.  From a development standpoint, seems like good practice
