### ISSUE TITLE
test datasets should include multiple libraries/samples

### ISSUE THREAD

**Issue by photocyte** [transXpress/transXpress-snakemake#2]
I've run into several cases while pipeline developing that it works with a single sample, but fails with multiple samples.  The test datasets should include multiple samples to help with debugging.

**Comment by tomas-pluskal** [comment]
Do you think splitting the current fastq (10K reads) into 2 x 5K reads is sufficient?

**Comment by photocyte** [comment]
Yes I would say so.  It's just a matter of having the multiple samples.

**Comment by tomas-pluskal** [comment]
Done in https://github.com/transXpress/transXpress-snakemake/commit/9442adec7981fc1ab0fd2fc6d3f59ebffc025303
