### ISSUE TITLE
Bio.Alphabet deprecated in latest Bioconda

### ISSUE THREAD

**Issue by mjacksonhill** [transXpress/transXpress-snakemake#24]
Bio.alphabet has been removed from the latest version of Biopython (seemingly as of 9/2020), which throws an error in newer installations of the transXpress prerequisites. Removing "import bio.alphabet" from the snakemake file seems to throw further 

https://biopython.org/wiki/Alphabet

There seem to be guidelines for replacing bio.alphabet here.

**Comment by tomas-pluskal** [comment]
Thanks Matthew!
Could you also upload the log files that were produced in the logs/ folder?

**Comment by mjacksonhill** [comment]
I think the error may have been me specifying the wrong file extension... running now again with a corrected samples.txt and waiting to see if it throws any errors.

**Comment by mjacksonhill** [comment]
I have a snippet of an error I'm getting in Kallisto here... not sure if related to bio.alphabet or if it's another error I'm getting. The initial bio.alphabet error seems to be resolved.
[kallisto_error.txt](https://github.com/transXpress/transXpress-snakemake/files/5462593/kallisto_error.txt)

**Comment by tomas-pluskal** [comment]
Should be fixed in the current master branch
