### ISSUE TITLE
Move trimmomatic out of Trinity?

### ISSUE THREAD

**Issue by photocyte** [transXpress/transXpress-snakemake#4]
trimmomatic is currently executed within the Trinity script.  There can be a bit more control if Trimmomatic is executed outside of Trinity, and it presumably would have better parallelization for many samples as well.  Running trimmomatic in its own jobs would also be better suited for forward compatability with other assemblers.

That being said, Trinity will utilize the unpaired filtered samples for de-bruijn graph construction when trimmomatic is internal.  I haven't been able to see if you can provide the unpaired filtered samples to trinity when trimming is done externally.

**Comment by tomas-pluskal** [comment]
It also means we'll have to reimplement some of the internal logic in Trinity, because the samples.txt file can contain both paired and unpaired libraries. You're right that for using different assemblers it will be necessary.

**Comment by photocyte** [comment]
I'll play around with Snakemake for the other issue (prefix naming), and see how complicated it is.  Will try to implement it, but if I can't figure it out, push it to the 2.0 milestone.

Currently the Nextflow pipeline has a "convert samples to relative" process which handles resetting the samples.txt file to refer to a relatively placed filtered reads file.
https://github.com/transXpress/transXpress-nextflow/blob/master/tests/test_nonSS-trinity/test_nonSS_dag.svg

Worth mentioning, the inclusion of the unpaired libraries probably isn't so important.  They are usually the minority of the data, and my expectation would be that they contain the majority of the weird sequencing issues (chimeric reads etc.)

**Comment by tomas-pluskal** [comment]
Done in #7
